export enum ErrorCode {
  //TOKEN
  TNPK = "NO PRIVATE KEY",
  TUTGT = "UNABLE TO GENERATE TOKEN",
  //AUTH
  ACNFU = "CAN NOT FIND USER",
  APDNM = "PASSWORDS DO NOT MATCH",
  //SIGNUP
  SUPIR = "PASSWORD IS REQUIRED",
  SUPSHMTCALOSCOBCONOSC = "PASSWORD SHOULD HAVE MINIMUM TEN CHARACTERS,AT LEAST ONE SMALL CHARACTER, ONE BIG CHARACTER, ONE NUMBER, ONE SPECIAL CHARACTER",
  SUEIR = "EMAIL IS REQUIRED",
  SUTEIAIU = "THIS EMAIL IS ALREADY IN USE",
  SUFNIR = "FIRST NAME IS REQUIRED",
  SULNIR = "LAST NAME IS REQUIRED",
  // USER
  UNVII = "NO VALID ID INCLUDED",
  //TASK
  TTIR = "TITLE IS REQUIRED",
  TTMBMFC = "TITLE MUST BE MINIMUM FIVE CHARACTERS",
  //DICTS
  DVCNBD = "DICT VALUES CAN NOT BE DUPLICATED",
  DVDNE = "DICT VALUE DOES NOT EXIST",
  //PROJECT
  PKIR = "KEY IS REQUIRED",
  PKMBMTC = "KEY MUST BE MAX TEN CHARACTERS",
  PNIR = "NAME IS REQUIRED",
  PTIR = "TYPE IS REQUIRED",
  PTME = "TYPE MUST EXIST",
  PMTIR = "MANAGEMENT TYPE IS REQUIRED",
  PMTME = "MANAGEMENT TYPE MUST EXIST",
  PUIPTIR = "USER IN PROJECT TYPE IS REQUIRED",
  PUIPTME = "USER IN PROJECT TYPE MUST EXIST",
}
