export enum ErrorCode {
  //TOKEN
  TOKEN_NPK = "NO PRIVATE KEY",
  TOKEN_UTGT = "UNABLE TO GENERATE TOKEN",
  TOKEN_TE = "TOKEN EXPIRED",
  TOKEN_WT = "TOKEN WRONG TOKEN",

  //AUTH
  AUTH_PDNM = "PASSWORDS DO NOT MATCH",
  AUTH_PIR = "PASSWORD IS REQUIRED",
  AUTH_PSHMTCALOSCOBCONOSC = "PASSWORD SHOULD HAVE MINIMUM TEN CHARACTERS,AT LEAST ONE SMALL CHARACTER, ONE BIG CHARACTER, ONE NUMBER, ONE SPECIAL CHARACTER",
  AUTH_EIR = "EMAIL IS REQUIRED",
  AUTH_TEIAIU = "THIS EMAIL IS ALREADY IN USE",
  AUTH_FNIR = "FIRST NAME IS REQUIRED",
  AUTH_LNIR = "LAST NAME IS REQUIRED",
  AUTH_CNFU = "CAN NOT FIND USER",

  // USER
  USER_NVII = "NO VALID ID INCLUDED",
  USER_CNFU = "CAN NOT FIND USER",

  //TASK
  TASK_TIR = "TITLE IS REQUIRED",
  TASK_TMBMFC = "TITLE MUST BE MINIMUM FIVE CHARACTERS",
  TASK_TTIR = "TASK TYPE IS REQUIRED",
  TASK_TECNHPT = "TYPE EPIC CAN NOT HAVE PARENT TASK",
  TASK_TME = "Task must exist",
  TASK_TTCNHC = "This task can not have children",
  TASK_TSME = "Task status must exist",

  //PROJECT
  PROJECT_KIR = "KEY IS REQUIRED",
  PROJECT_KMBMTC = "KEY MUST BE MAX TEN CHARACTERS",
  PROJECT_NIR = "NAME IS REQUIRED",
  PROJECT_TIR = "PROJECT TYPE IS REQUIRED",
  PROJECT_MTIR = "PROJECT MANAGEMENT TYPE IS REQUIRED",
  PROJECT_UIPTIR = "USER IN PROJECT TYPE IS REQUIRED",
  PROJECT_NLME = "NEW LEADER MUST EXIST",
  PROJECT_PME = "PROJECT MUST EXIST",
  PROJECT_YMPMOVTC = "YOU MUST PROVIDE MINIMUM ONE VALUE TO CHANGE",
  PROJECT_IIR = "PROJECT ID IS REQUIRED",
  PROJECT_LIIR = "PROJECT LEADER ID IS REQUIRED",
  PROJECT_PDSE = "Project does not exist",
  PROJECT_UINMOTP = "User is not member of this project",

  //SERVER
  SERVER_ISE = "Internal server error",
  SERVER_PNF = "Path not found",
  SERVER_UNA = "Unauthorized",
  SERVER_FOR = "Forbidden",
}

export type ServerError = {
  message: ErrorCode;
};
