export enum ErrorCode {
  //TOKEN
  TNPK = "NO PRIVATE KEY",
  TUTGT = "UNABLE TO GENERATE TOKEN",
  TTE = "TOKEN EXPIRED",
  //AUTH
  APDNM = "PASSWORDS DO NOT MATCH",
  //SIGNUP
  SUPIR = "PASSWORD IS REQUIRED",
  SUPSHMTCALOSCOBCONOSC = "PASSWORD SHOULD HAVE MINIMUM TEN CHARACTERS,AT LEAST ONE SMALL CHARACTER, ONE BIG CHARACTER, ONE NUMBER, ONE SPECIAL CHARACTER",
  SUEIR = "EMAIL IS REQUIRED",
  SUTEIAIU = "THIS EMAIL IS ALREADY IN USE",
  SUFNIR = "FIRST NAME IS REQUIRED",
  SULNIR = "LAST NAME IS REQUIRED",
  // USER
  UNVII = "NO VALID ID INCLUDED",
  UCNFU = "CAN NOT FIND USER",
  //TASK
  TTIR = "TITLE IS REQUIRED",
  TTMBMFC = "TITLE MUST BE MINIMUM FIVE CHARACTERS",
  //PROJECT
  PKIR = "KEY IS REQUIRED",
  PKMBMTC = "KEY MUST BE MAX TEN CHARACTERS",
  PNIR = "NAME IS REQUIRED",
  PTIR = "PROJECT TYPE IS REQUIRED",
  PMTIR = "PROJECT MANAGEMENT TYPE IS REQUIRED",
  PUIPTIR = "USER IN PROJECT TYPE IS REQUIRED",
  PNLME = "NEW LEADER MUST EXIST",
  PPME = "PROJECT MUST EXIST",
  PYMPMOVTC = "YOU MUST PROVIDE MINIMUM ONE VALUE TO CHANGE",
}
